# This is a basic workflow to help you get started with Actions
name: "Connect to an AWS role from a GitHub repository"


on:
  push:
    branches: 
      - main
  # merge changes from one branch into another
  pull_request:
      # Permission can be added at job level or workflow level   
permissions: 
     id-token: write
     contents: read 


env:

    AWS_REGION : ${{ secrets.AWS_REGION }}




jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
    # github is cloning the repository and has access to the files
      - name: Git checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity